require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VirtualsController do

  # This should return the minimal set of attributes required to create a valid
  # Virtual. As you add validations to Virtual, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all virtuals as @virtuals" do
      virtual = Virtual.create! valid_attributes
      get :index
      assigns(:virtuals).should eq([virtual])
    end
  end

  describe "GET show" do
    it "assigns the requested virtual as @virtual" do
      virtual = Virtual.create! valid_attributes
      get :show, :id => virtual.id.to_s
      assigns(:virtual).should eq(virtual)
    end
  end

  describe "GET new" do
    it "assigns a new virtual as @virtual" do
      get :new
      assigns(:virtual).should be_a_new(Virtual)
    end
  end

  describe "GET edit" do
    it "assigns the requested virtual as @virtual" do
      virtual = Virtual.create! valid_attributes
      get :edit, :id => virtual.id.to_s
      assigns(:virtual).should eq(virtual)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Virtual" do
        expect {
          post :create, :virtual => valid_attributes
        }.to change(Virtual, :count).by(1)
      end

      it "assigns a newly created virtual as @virtual" do
        post :create, :virtual => valid_attributes
        assigns(:virtual).should be_a(Virtual)
        assigns(:virtual).should be_persisted
      end

      it "redirects to the created virtual" do
        post :create, :virtual => valid_attributes
        response.should redirect_to(Virtual.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved virtual as @virtual" do
        # Trigger the behavior that occurs when invalid params are submitted
        Virtual.any_instance.stub(:save).and_return(false)
        post :create, :virtual => {}
        assigns(:virtual).should be_a_new(Virtual)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Virtual.any_instance.stub(:save).and_return(false)
        post :create, :virtual => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested virtual" do
        virtual = Virtual.create! valid_attributes
        # Assuming there are no other virtuals in the database, this
        # specifies that the Virtual created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Virtual.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => virtual.id, :virtual => {'these' => 'params'}
      end

      it "assigns the requested virtual as @virtual" do
        virtual = Virtual.create! valid_attributes
        put :update, :id => virtual.id, :virtual => valid_attributes
        assigns(:virtual).should eq(virtual)
      end

      it "redirects to the virtual" do
        virtual = Virtual.create! valid_attributes
        put :update, :id => virtual.id, :virtual => valid_attributes
        response.should redirect_to(virtual)
      end
    end

    describe "with invalid params" do
      it "assigns the virtual as @virtual" do
        virtual = Virtual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Virtual.any_instance.stub(:save).and_return(false)
        put :update, :id => virtual.id.to_s, :virtual => {}
        assigns(:virtual).should eq(virtual)
      end

      it "re-renders the 'edit' template" do
        virtual = Virtual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Virtual.any_instance.stub(:save).and_return(false)
        put :update, :id => virtual.id.to_s, :virtual => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested virtual" do
      virtual = Virtual.create! valid_attributes
      expect {
        delete :destroy, :id => virtual.id.to_s
      }.to change(Virtual, :count).by(-1)
    end

    it "redirects to the virtuals list" do
      virtual = Virtual.create! valid_attributes
      delete :destroy, :id => virtual.id.to_s
      response.should redirect_to(virtuals_url)
    end
  end

end
